#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_dhxt")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertAdmin(Admin instance);
  partial void UpdateAdmin(Admin instance);
  partial void DeleteAdmin(Admin instance);
  partial void InsertPayment(Payment instance);
  partial void UpdatePayment(Payment instance);
  partial void DeletePayment(Payment instance);
  partial void InsertVIP(VIP instance);
  partial void UpdateVIP(VIP instance);
  partial void DeleteVIP(VIP instance);
  partial void InsertPayment1(Payment1 instance);
  partial void UpdatePayment1(Payment1 instance);
  partial void DeletePayment1(Payment1 instance);
  partial void InsertVIP1(VIP1 instance);
  partial void UpdateVIP1(VIP1 instance);
  partial void DeleteVIP1(VIP1 instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_dhxtConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<QueueView> QueueView
	{
		get
		{
			return this.GetTable<QueueView>();
		}
	}
	
	public System.Data.Linq.Table<DeQueueView> DeQueueView
	{
		get
		{
			return this.GetTable<DeQueueView>();
		}
	}
	
	public System.Data.Linq.Table<Admin> Admin
	{
		get
		{
			return this.GetTable<Admin>();
		}
	}
	
	public System.Data.Linq.Table<Payment> Payment
	{
		get
		{
			return this.GetTable<Payment>();
		}
	}
	
	public System.Data.Linq.Table<VIP> VIP
	{
		get
		{
			return this.GetTable<VIP>();
		}
	}
	
	public System.Data.Linq.Table<Payment1> Payment1
	{
		get
		{
			return this.GetTable<Payment1>();
		}
	}
	
	public System.Data.Linq.Table<VIP1> VIP1
	{
		get
		{
			return this.GetTable<VIP1>();
		}
	}
	
	public System.Data.Linq.Table<DeQueueView1> DeQueueView1
	{
		get
		{
			return this.GetTable<DeQueueView1>();
		}
	}
	
	public System.Data.Linq.Table<QueueView1> QueueView1
	{
		get
		{
			return this.GetTable<QueueView1>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QueueView")]
public partial class QueueView
{
	
	private int _PayID;
	
	private string _VIPNo;
	
	private string _Phone;
	
	private string _RefereeNo;
	
	private string _Bank;
	
	private string _CardNo;
	
	private string _CardHolder;
	
	private string _PayJpg;
	
	private string _PaySpecify;
	
	private int _ActiveState;
	
	private int _QueueNo;
	
	private int _DeQueue;
	
	private string _Checker;
	
	public QueueView()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int PayID
	{
		get
		{
			return this._PayID;
		}
		set
		{
			if ((this._PayID != value))
			{
				this._PayID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPNo", DbType="VarChar(10)")]
	public string VIPNo
	{
		get
		{
			return this._VIPNo;
		}
		set
		{
			if ((this._VIPNo != value))
			{
				this._VIPNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this._Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefereeNo", DbType="VarChar(10)")]
	public string RefereeNo
	{
		get
		{
			return this._RefereeNo;
		}
		set
		{
			if ((this._RefereeNo != value))
			{
				this._RefereeNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank", DbType="VarChar(80)")]
	public string Bank
	{
		get
		{
			return this._Bank;
		}
		set
		{
			if ((this._Bank != value))
			{
				this._Bank = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="VarChar(30)")]
	public string CardNo
	{
		get
		{
			return this._CardNo;
		}
		set
		{
			if ((this._CardNo != value))
			{
				this._CardNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardHolder", DbType="VarChar(20)")]
	public string CardHolder
	{
		get
		{
			return this._CardHolder;
		}
		set
		{
			if ((this._CardHolder != value))
			{
				this._CardHolder = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayJpg", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string PayJpg
	{
		get
		{
			return this._PayJpg;
		}
		set
		{
			if ((this._PayJpg != value))
			{
				this._PayJpg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaySpecify", DbType="VarChar(180)")]
	public string PaySpecify
	{
		get
		{
			return this._PaySpecify;
		}
		set
		{
			if ((this._PaySpecify != value))
			{
				this._PaySpecify = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveState", DbType="Int NOT NULL")]
	public int ActiveState
	{
		get
		{
			return this._ActiveState;
		}
		set
		{
			if ((this._ActiveState != value))
			{
				this._ActiveState = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueueNo", DbType="Int NOT NULL")]
	public int QueueNo
	{
		get
		{
			return this._QueueNo;
		}
		set
		{
			if ((this._QueueNo != value))
			{
				this._QueueNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeQueue", DbType="Int NOT NULL")]
	public int DeQueue
	{
		get
		{
			return this._DeQueue;
		}
		set
		{
			if ((this._DeQueue != value))
			{
				this._DeQueue = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checker", DbType="VarChar(20)")]
	public string Checker
	{
		get
		{
			return this._Checker;
		}
		set
		{
			if ((this._Checker != value))
			{
				this._Checker = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeQueueView")]
public partial class DeQueueView
{
	
	private int _PayID;
	
	private string _VIPNo;
	
	private string _Phone;
	
	private string _RefereeNo;
	
	private string _Bank;
	
	private string _CardNo;
	
	private string _CardHolder;
	
	private string _PayJpg;
	
	private string _PaySpecify;
	
	private int _ActiveState;
	
	private int _QueueNo;
	
	private int _DeQueue;
	
	private string _Checker;
	
	public DeQueueView()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int PayID
	{
		get
		{
			return this._PayID;
		}
		set
		{
			if ((this._PayID != value))
			{
				this._PayID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPNo", DbType="VarChar(10)")]
	public string VIPNo
	{
		get
		{
			return this._VIPNo;
		}
		set
		{
			if ((this._VIPNo != value))
			{
				this._VIPNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this._Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefereeNo", DbType="VarChar(10)")]
	public string RefereeNo
	{
		get
		{
			return this._RefereeNo;
		}
		set
		{
			if ((this._RefereeNo != value))
			{
				this._RefereeNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank", DbType="VarChar(80)")]
	public string Bank
	{
		get
		{
			return this._Bank;
		}
		set
		{
			if ((this._Bank != value))
			{
				this._Bank = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="VarChar(30)")]
	public string CardNo
	{
		get
		{
			return this._CardNo;
		}
		set
		{
			if ((this._CardNo != value))
			{
				this._CardNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardHolder", DbType="VarChar(20)")]
	public string CardHolder
	{
		get
		{
			return this._CardHolder;
		}
		set
		{
			if ((this._CardHolder != value))
			{
				this._CardHolder = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayJpg", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string PayJpg
	{
		get
		{
			return this._PayJpg;
		}
		set
		{
			if ((this._PayJpg != value))
			{
				this._PayJpg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaySpecify", DbType="VarChar(180)")]
	public string PaySpecify
	{
		get
		{
			return this._PaySpecify;
		}
		set
		{
			if ((this._PaySpecify != value))
			{
				this._PaySpecify = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveState", DbType="Int NOT NULL")]
	public int ActiveState
	{
		get
		{
			return this._ActiveState;
		}
		set
		{
			if ((this._ActiveState != value))
			{
				this._ActiveState = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueueNo", DbType="Int NOT NULL")]
	public int QueueNo
	{
		get
		{
			return this._QueueNo;
		}
		set
		{
			if ((this._QueueNo != value))
			{
				this._QueueNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeQueue", DbType="Int NOT NULL")]
	public int DeQueue
	{
		get
		{
			return this._DeQueue;
		}
		set
		{
			if ((this._DeQueue != value))
			{
				this._DeQueue = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checker", DbType="VarChar(20)")]
	public string Checker
	{
		get
		{
			return this._Checker;
		}
		set
		{
			if ((this._Checker != value))
			{
				this._Checker = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _AdminID;
	
	private string _AdminName;
	
	private string _LoginName;
	
	private string _PW;
	
	private System.Nullable<bool> _Permission;
	
	private string _Phone;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdminIDChanging(int value);
    partial void OnAdminIDChanged();
    partial void OnAdminNameChanging(string value);
    partial void OnAdminNameChanged();
    partial void OnLoginNameChanging(string value);
    partial void OnLoginNameChanged();
    partial void OnPWChanging(string value);
    partial void OnPWChanged();
    partial void OnPermissionChanging(System.Nullable<bool> value);
    partial void OnPermissionChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    #endregion
	
	public Admin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int AdminID
	{
		get
		{
			return this._AdminID;
		}
		set
		{
			if ((this._AdminID != value))
			{
				this.OnAdminIDChanging(value);
				this.SendPropertyChanging();
				this._AdminID = value;
				this.SendPropertyChanged("AdminID");
				this.OnAdminIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminName", DbType="VarChar(20)")]
	public string AdminName
	{
		get
		{
			return this._AdminName;
		}
		set
		{
			if ((this._AdminName != value))
			{
				this.OnAdminNameChanging(value);
				this.SendPropertyChanging();
				this._AdminName = value;
				this.SendPropertyChanged("AdminName");
				this.OnAdminNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginName", DbType="VarChar(20)")]
	public string LoginName
	{
		get
		{
			return this._LoginName;
		}
		set
		{
			if ((this._LoginName != value))
			{
				this.OnLoginNameChanging(value);
				this.SendPropertyChanging();
				this._LoginName = value;
				this.SendPropertyChanged("LoginName");
				this.OnLoginNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PW", DbType="VarChar(10)")]
	public string PW
	{
		get
		{
			return this._PW;
		}
		set
		{
			if ((this._PW != value))
			{
				this.OnPWChanging(value);
				this.SendPropertyChanging();
				this._PW = value;
				this.SendPropertyChanged("PW");
				this.OnPWChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permission", DbType="Bit")]
	public System.Nullable<bool> Permission
	{
		get
		{
			return this._Permission;
		}
		set
		{
			if ((this._Permission != value))
			{
				this.OnPermissionChanging(value);
				this.SendPropertyChanging();
				this._Permission = value;
				this.SendPropertyChanged("Permission");
				this.OnPermissionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Payment")]
public partial class Payment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _PayID;
	
	private string _VIPNo;
	
	private string _Phone;
	
	private string _RefereeNo;
	
	private string _Bank;
	
	private string _CardNo;
	
	private string _CardHolder;
	
	private string _PayJpg;
	
	private string _PaySpecify;
	
	private int _ActiveState;
	
	private int _QueueNo;
	
	private int _DeQueue;
	
	private string _Checker;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPayIDChanging(int value);
    partial void OnPayIDChanged();
    partial void OnVIPNoChanging(string value);
    partial void OnVIPNoChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnRefereeNoChanging(string value);
    partial void OnRefereeNoChanged();
    partial void OnBankChanging(string value);
    partial void OnBankChanged();
    partial void OnCardNoChanging(string value);
    partial void OnCardNoChanged();
    partial void OnCardHolderChanging(string value);
    partial void OnCardHolderChanged();
    partial void OnPayJpgChanging(string value);
    partial void OnPayJpgChanged();
    partial void OnPaySpecifyChanging(string value);
    partial void OnPaySpecifyChanged();
    partial void OnActiveStateChanging(int value);
    partial void OnActiveStateChanged();
    partial void OnQueueNoChanging(int value);
    partial void OnQueueNoChanged();
    partial void OnDeQueueChanging(int value);
    partial void OnDeQueueChanged();
    partial void OnCheckerChanging(string value);
    partial void OnCheckerChanged();
    #endregion
	
	public Payment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int PayID
	{
		get
		{
			return this._PayID;
		}
		set
		{
			if ((this._PayID != value))
			{
				this.OnPayIDChanging(value);
				this.SendPropertyChanging();
				this._PayID = value;
				this.SendPropertyChanged("PayID");
				this.OnPayIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPNo", DbType="VarChar(10)")]
	public string VIPNo
	{
		get
		{
			return this._VIPNo;
		}
		set
		{
			if ((this._VIPNo != value))
			{
				this.OnVIPNoChanging(value);
				this.SendPropertyChanging();
				this._VIPNo = value;
				this.SendPropertyChanged("VIPNo");
				this.OnVIPNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefereeNo", DbType="VarChar(10)")]
	public string RefereeNo
	{
		get
		{
			return this._RefereeNo;
		}
		set
		{
			if ((this._RefereeNo != value))
			{
				this.OnRefereeNoChanging(value);
				this.SendPropertyChanging();
				this._RefereeNo = value;
				this.SendPropertyChanged("RefereeNo");
				this.OnRefereeNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank", DbType="VarChar(80)")]
	public string Bank
	{
		get
		{
			return this._Bank;
		}
		set
		{
			if ((this._Bank != value))
			{
				this.OnBankChanging(value);
				this.SendPropertyChanging();
				this._Bank = value;
				this.SendPropertyChanged("Bank");
				this.OnBankChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="VarChar(30)")]
	public string CardNo
	{
		get
		{
			return this._CardNo;
		}
		set
		{
			if ((this._CardNo != value))
			{
				this.OnCardNoChanging(value);
				this.SendPropertyChanging();
				this._CardNo = value;
				this.SendPropertyChanged("CardNo");
				this.OnCardNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardHolder", DbType="VarChar(20)")]
	public string CardHolder
	{
		get
		{
			return this._CardHolder;
		}
		set
		{
			if ((this._CardHolder != value))
			{
				this.OnCardHolderChanging(value);
				this.SendPropertyChanging();
				this._CardHolder = value;
				this.SendPropertyChanged("CardHolder");
				this.OnCardHolderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayJpg", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string PayJpg
	{
		get
		{
			return this._PayJpg;
		}
		set
		{
			if ((this._PayJpg != value))
			{
				this.OnPayJpgChanging(value);
				this.SendPropertyChanging();
				this._PayJpg = value;
				this.SendPropertyChanged("PayJpg");
				this.OnPayJpgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaySpecify", DbType="VarChar(180)")]
	public string PaySpecify
	{
		get
		{
			return this._PaySpecify;
		}
		set
		{
			if ((this._PaySpecify != value))
			{
				this.OnPaySpecifyChanging(value);
				this.SendPropertyChanging();
				this._PaySpecify = value;
				this.SendPropertyChanged("PaySpecify");
				this.OnPaySpecifyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveState", DbType="Int NOT NULL")]
	public int ActiveState
	{
		get
		{
			return this._ActiveState;
		}
		set
		{
			if ((this._ActiveState != value))
			{
				this.OnActiveStateChanging(value);
				this.SendPropertyChanging();
				this._ActiveState = value;
				this.SendPropertyChanged("ActiveState");
				this.OnActiveStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueueNo", DbType="Int NOT NULL")]
	public int QueueNo
	{
		get
		{
			return this._QueueNo;
		}
		set
		{
			if ((this._QueueNo != value))
			{
				this.OnQueueNoChanging(value);
				this.SendPropertyChanging();
				this._QueueNo = value;
				this.SendPropertyChanged("QueueNo");
				this.OnQueueNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeQueue", DbType="Int NOT NULL")]
	public int DeQueue
	{
		get
		{
			return this._DeQueue;
		}
		set
		{
			if ((this._DeQueue != value))
			{
				this.OnDeQueueChanging(value);
				this.SendPropertyChanging();
				this._DeQueue = value;
				this.SendPropertyChanged("DeQueue");
				this.OnDeQueueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checker", DbType="VarChar(20)")]
	public string Checker
	{
		get
		{
			return this._Checker;
		}
		set
		{
			if ((this._Checker != value))
			{
				this.OnCheckerChanging(value);
				this.SendPropertyChanging();
				this._Checker = value;
				this.SendPropertyChanged("Checker");
				this.OnCheckerChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIP")]
public partial class VIP : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _VIPNo;
	
	private string _VIPName;
	
	private string _LoginName;
	
	private string _PW;
	
	private string _Phone;
	
	private System.Nullable<int> _RefereeCount;
	
	private string _email;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVIPNoChanging(string value);
    partial void OnVIPNoChanged();
    partial void OnVIPNameChanging(string value);
    partial void OnVIPNameChanged();
    partial void OnLoginNameChanging(string value);
    partial void OnLoginNameChanged();
    partial void OnPWChanging(string value);
    partial void OnPWChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnRefereeCountChanging(System.Nullable<int> value);
    partial void OnRefereeCountChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
	
	public VIP()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPNo", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string VIPNo
	{
		get
		{
			return this._VIPNo;
		}
		set
		{
			if ((this._VIPNo != value))
			{
				this.OnVIPNoChanging(value);
				this.SendPropertyChanging();
				this._VIPNo = value;
				this.SendPropertyChanged("VIPNo");
				this.OnVIPNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPName", DbType="VarChar(20)")]
	public string VIPName
	{
		get
		{
			return this._VIPName;
		}
		set
		{
			if ((this._VIPName != value))
			{
				this.OnVIPNameChanging(value);
				this.SendPropertyChanging();
				this._VIPName = value;
				this.SendPropertyChanged("VIPName");
				this.OnVIPNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginName", DbType="VarChar(20)")]
	public string LoginName
	{
		get
		{
			return this._LoginName;
		}
		set
		{
			if ((this._LoginName != value))
			{
				this.OnLoginNameChanging(value);
				this.SendPropertyChanging();
				this._LoginName = value;
				this.SendPropertyChanged("LoginName");
				this.OnLoginNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PW", DbType="VarChar(10)")]
	public string PW
	{
		get
		{
			return this._PW;
		}
		set
		{
			if ((this._PW != value))
			{
				this.OnPWChanging(value);
				this.SendPropertyChanging();
				this._PW = value;
				this.SendPropertyChanged("PW");
				this.OnPWChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefereeCount", DbType="Int")]
	public System.Nullable<int> RefereeCount
	{
		get
		{
			return this._RefereeCount;
		}
		set
		{
			if ((this._RefereeCount != value))
			{
				this.OnRefereeCountChanging(value);
				this.SendPropertyChanging();
				this._RefereeCount = value;
				this.SendPropertyChanged("RefereeCount");
				this.OnRefereeCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Payment1")]
public partial class Payment1 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _PayID;
	
	private string _VIPNo;
	
	private string _Phone;
	
	private string _RefereeNo;
	
	private string _Bank;
	
	private string _CardNo;
	
	private string _CardHolder;
	
	private string _PayJpg;
	
	private string _PaySpecify;
	
	private int _ActiveState;
	
	private int _QueueNo;
	
	private int _DeQueue;
	
	private string _Checker;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPayIDChanging(int value);
    partial void OnPayIDChanged();
    partial void OnVIPNoChanging(string value);
    partial void OnVIPNoChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnRefereeNoChanging(string value);
    partial void OnRefereeNoChanged();
    partial void OnBankChanging(string value);
    partial void OnBankChanged();
    partial void OnCardNoChanging(string value);
    partial void OnCardNoChanged();
    partial void OnCardHolderChanging(string value);
    partial void OnCardHolderChanged();
    partial void OnPayJpgChanging(string value);
    partial void OnPayJpgChanged();
    partial void OnPaySpecifyChanging(string value);
    partial void OnPaySpecifyChanged();
    partial void OnActiveStateChanging(int value);
    partial void OnActiveStateChanged();
    partial void OnQueueNoChanging(int value);
    partial void OnQueueNoChanged();
    partial void OnDeQueueChanging(int value);
    partial void OnDeQueueChanged();
    partial void OnCheckerChanging(string value);
    partial void OnCheckerChanged();
    #endregion
	
	public Payment1()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int PayID
	{
		get
		{
			return this._PayID;
		}
		set
		{
			if ((this._PayID != value))
			{
				this.OnPayIDChanging(value);
				this.SendPropertyChanging();
				this._PayID = value;
				this.SendPropertyChanged("PayID");
				this.OnPayIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPNo", DbType="VarChar(10)")]
	public string VIPNo
	{
		get
		{
			return this._VIPNo;
		}
		set
		{
			if ((this._VIPNo != value))
			{
				this.OnVIPNoChanging(value);
				this.SendPropertyChanging();
				this._VIPNo = value;
				this.SendPropertyChanged("VIPNo");
				this.OnVIPNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefereeNo", DbType="VarChar(10)")]
	public string RefereeNo
	{
		get
		{
			return this._RefereeNo;
		}
		set
		{
			if ((this._RefereeNo != value))
			{
				this.OnRefereeNoChanging(value);
				this.SendPropertyChanging();
				this._RefereeNo = value;
				this.SendPropertyChanged("RefereeNo");
				this.OnRefereeNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank", DbType="VarChar(80)")]
	public string Bank
	{
		get
		{
			return this._Bank;
		}
		set
		{
			if ((this._Bank != value))
			{
				this.OnBankChanging(value);
				this.SendPropertyChanging();
				this._Bank = value;
				this.SendPropertyChanged("Bank");
				this.OnBankChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="VarChar(30)")]
	public string CardNo
	{
		get
		{
			return this._CardNo;
		}
		set
		{
			if ((this._CardNo != value))
			{
				this.OnCardNoChanging(value);
				this.SendPropertyChanging();
				this._CardNo = value;
				this.SendPropertyChanged("CardNo");
				this.OnCardNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardHolder", DbType="VarChar(20)")]
	public string CardHolder
	{
		get
		{
			return this._CardHolder;
		}
		set
		{
			if ((this._CardHolder != value))
			{
				this.OnCardHolderChanging(value);
				this.SendPropertyChanging();
				this._CardHolder = value;
				this.SendPropertyChanged("CardHolder");
				this.OnCardHolderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayJpg", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string PayJpg
	{
		get
		{
			return this._PayJpg;
		}
		set
		{
			if ((this._PayJpg != value))
			{
				this.OnPayJpgChanging(value);
				this.SendPropertyChanging();
				this._PayJpg = value;
				this.SendPropertyChanged("PayJpg");
				this.OnPayJpgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaySpecify", DbType="VarChar(180)")]
	public string PaySpecify
	{
		get
		{
			return this._PaySpecify;
		}
		set
		{
			if ((this._PaySpecify != value))
			{
				this.OnPaySpecifyChanging(value);
				this.SendPropertyChanging();
				this._PaySpecify = value;
				this.SendPropertyChanged("PaySpecify");
				this.OnPaySpecifyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveState", DbType="Int NOT NULL")]
	public int ActiveState
	{
		get
		{
			return this._ActiveState;
		}
		set
		{
			if ((this._ActiveState != value))
			{
				this.OnActiveStateChanging(value);
				this.SendPropertyChanging();
				this._ActiveState = value;
				this.SendPropertyChanged("ActiveState");
				this.OnActiveStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueueNo", DbType="Int NOT NULL")]
	public int QueueNo
	{
		get
		{
			return this._QueueNo;
		}
		set
		{
			if ((this._QueueNo != value))
			{
				this.OnQueueNoChanging(value);
				this.SendPropertyChanging();
				this._QueueNo = value;
				this.SendPropertyChanged("QueueNo");
				this.OnQueueNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeQueue", DbType="Int NOT NULL")]
	public int DeQueue
	{
		get
		{
			return this._DeQueue;
		}
		set
		{
			if ((this._DeQueue != value))
			{
				this.OnDeQueueChanging(value);
				this.SendPropertyChanging();
				this._DeQueue = value;
				this.SendPropertyChanged("DeQueue");
				this.OnDeQueueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checker", DbType="VarChar(20)")]
	public string Checker
	{
		get
		{
			return this._Checker;
		}
		set
		{
			if ((this._Checker != value))
			{
				this.OnCheckerChanging(value);
				this.SendPropertyChanging();
				this._Checker = value;
				this.SendPropertyChanged("Checker");
				this.OnCheckerChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIP1")]
public partial class VIP1 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _VIPNo;
	
	private string _VIPName;
	
	private string _LoginName;
	
	private string _PW;
	
	private string _Phone;
	
	private System.Nullable<int> _RefereeCount;
	
	private string _email;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVIPNoChanging(string value);
    partial void OnVIPNoChanged();
    partial void OnVIPNameChanging(string value);
    partial void OnVIPNameChanged();
    partial void OnLoginNameChanging(string value);
    partial void OnLoginNameChanged();
    partial void OnPWChanging(string value);
    partial void OnPWChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnRefereeCountChanging(System.Nullable<int> value);
    partial void OnRefereeCountChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
	
	public VIP1()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPNo", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string VIPNo
	{
		get
		{
			return this._VIPNo;
		}
		set
		{
			if ((this._VIPNo != value))
			{
				this.OnVIPNoChanging(value);
				this.SendPropertyChanging();
				this._VIPNo = value;
				this.SendPropertyChanged("VIPNo");
				this.OnVIPNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPName", DbType="VarChar(20)")]
	public string VIPName
	{
		get
		{
			return this._VIPName;
		}
		set
		{
			if ((this._VIPName != value))
			{
				this.OnVIPNameChanging(value);
				this.SendPropertyChanging();
				this._VIPName = value;
				this.SendPropertyChanged("VIPName");
				this.OnVIPNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginName", DbType="VarChar(20)")]
	public string LoginName
	{
		get
		{
			return this._LoginName;
		}
		set
		{
			if ((this._LoginName != value))
			{
				this.OnLoginNameChanging(value);
				this.SendPropertyChanging();
				this._LoginName = value;
				this.SendPropertyChanged("LoginName");
				this.OnLoginNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PW", DbType="VarChar(10)")]
	public string PW
	{
		get
		{
			return this._PW;
		}
		set
		{
			if ((this._PW != value))
			{
				this.OnPWChanging(value);
				this.SendPropertyChanging();
				this._PW = value;
				this.SendPropertyChanged("PW");
				this.OnPWChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefereeCount", DbType="Int")]
	public System.Nullable<int> RefereeCount
	{
		get
		{
			return this._RefereeCount;
		}
		set
		{
			if ((this._RefereeCount != value))
			{
				this.OnRefereeCountChanging(value);
				this.SendPropertyChanging();
				this._RefereeCount = value;
				this.SendPropertyChanged("RefereeCount");
				this.OnRefereeCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeQueueView1")]
public partial class DeQueueView1
{
	
	private int _PayID;
	
	private string _VIPNo;
	
	private string _Phone;
	
	private string _RefereeNo;
	
	private string _Bank;
	
	private string _CardNo;
	
	private string _CardHolder;
	
	private string _PayJpg;
	
	private string _PaySpecify;
	
	private int _ActiveState;
	
	private int _QueueNo;
	
	private int _DeQueue;
	
	private string _Checker;
	
	public DeQueueView1()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int PayID
	{
		get
		{
			return this._PayID;
		}
		set
		{
			if ((this._PayID != value))
			{
				this._PayID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPNo", DbType="VarChar(10)")]
	public string VIPNo
	{
		get
		{
			return this._VIPNo;
		}
		set
		{
			if ((this._VIPNo != value))
			{
				this._VIPNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this._Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefereeNo", DbType="VarChar(10)")]
	public string RefereeNo
	{
		get
		{
			return this._RefereeNo;
		}
		set
		{
			if ((this._RefereeNo != value))
			{
				this._RefereeNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank", DbType="VarChar(80)")]
	public string Bank
	{
		get
		{
			return this._Bank;
		}
		set
		{
			if ((this._Bank != value))
			{
				this._Bank = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="VarChar(30)")]
	public string CardNo
	{
		get
		{
			return this._CardNo;
		}
		set
		{
			if ((this._CardNo != value))
			{
				this._CardNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardHolder", DbType="VarChar(20)")]
	public string CardHolder
	{
		get
		{
			return this._CardHolder;
		}
		set
		{
			if ((this._CardHolder != value))
			{
				this._CardHolder = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayJpg", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string PayJpg
	{
		get
		{
			return this._PayJpg;
		}
		set
		{
			if ((this._PayJpg != value))
			{
				this._PayJpg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaySpecify", DbType="VarChar(180)")]
	public string PaySpecify
	{
		get
		{
			return this._PaySpecify;
		}
		set
		{
			if ((this._PaySpecify != value))
			{
				this._PaySpecify = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveState", DbType="Int NOT NULL")]
	public int ActiveState
	{
		get
		{
			return this._ActiveState;
		}
		set
		{
			if ((this._ActiveState != value))
			{
				this._ActiveState = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueueNo", DbType="Int NOT NULL")]
	public int QueueNo
	{
		get
		{
			return this._QueueNo;
		}
		set
		{
			if ((this._QueueNo != value))
			{
				this._QueueNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeQueue", DbType="Int NOT NULL")]
	public int DeQueue
	{
		get
		{
			return this._DeQueue;
		}
		set
		{
			if ((this._DeQueue != value))
			{
				this._DeQueue = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checker", DbType="VarChar(20)")]
	public string Checker
	{
		get
		{
			return this._Checker;
		}
		set
		{
			if ((this._Checker != value))
			{
				this._Checker = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QueueView1")]
public partial class QueueView1
{
	
	private int _PayID;
	
	private string _VIPNo;
	
	private string _Phone;
	
	private string _RefereeNo;
	
	private string _Bank;
	
	private string _CardNo;
	
	private string _CardHolder;
	
	private string _PayJpg;
	
	private string _PaySpecify;
	
	private int _ActiveState;
	
	private int _QueueNo;
	
	private int _DeQueue;
	
	private string _Checker;
	
	public QueueView1()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int PayID
	{
		get
		{
			return this._PayID;
		}
		set
		{
			if ((this._PayID != value))
			{
				this._PayID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIPNo", DbType="VarChar(10)")]
	public string VIPNo
	{
		get
		{
			return this._VIPNo;
		}
		set
		{
			if ((this._VIPNo != value))
			{
				this._VIPNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
	public string Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this._Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefereeNo", DbType="VarChar(10)")]
	public string RefereeNo
	{
		get
		{
			return this._RefereeNo;
		}
		set
		{
			if ((this._RefereeNo != value))
			{
				this._RefereeNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank", DbType="VarChar(80)")]
	public string Bank
	{
		get
		{
			return this._Bank;
		}
		set
		{
			if ((this._Bank != value))
			{
				this._Bank = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="VarChar(30)")]
	public string CardNo
	{
		get
		{
			return this._CardNo;
		}
		set
		{
			if ((this._CardNo != value))
			{
				this._CardNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardHolder", DbType="VarChar(20)")]
	public string CardHolder
	{
		get
		{
			return this._CardHolder;
		}
		set
		{
			if ((this._CardHolder != value))
			{
				this._CardHolder = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayJpg", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string PayJpg
	{
		get
		{
			return this._PayJpg;
		}
		set
		{
			if ((this._PayJpg != value))
			{
				this._PayJpg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaySpecify", DbType="VarChar(180)")]
	public string PaySpecify
	{
		get
		{
			return this._PaySpecify;
		}
		set
		{
			if ((this._PaySpecify != value))
			{
				this._PaySpecify = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveState", DbType="Int NOT NULL")]
	public int ActiveState
	{
		get
		{
			return this._ActiveState;
		}
		set
		{
			if ((this._ActiveState != value))
			{
				this._ActiveState = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueueNo", DbType="Int NOT NULL")]
	public int QueueNo
	{
		get
		{
			return this._QueueNo;
		}
		set
		{
			if ((this._QueueNo != value))
			{
				this._QueueNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeQueue", DbType="Int NOT NULL")]
	public int DeQueue
	{
		get
		{
			return this._DeQueue;
		}
		set
		{
			if ((this._DeQueue != value))
			{
				this._DeQueue = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checker", DbType="VarChar(20)")]
	public string Checker
	{
		get
		{
			return this._Checker;
		}
		set
		{
			if ((this._Checker != value))
			{
				this._Checker = value;
			}
		}
	}
}
#pragma warning restore 1591
